const N=window.NOORTOONA;
const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const stages=['المناسبة','التفاصيل','القالب','التصميم','الضيوف','المعاينة','الإرسال'];
const defaults={step:1,occasionKey:'wedding',activityKey:'padel',customOccasion:'',customActivity:'',template:'ليلة كحلية',name1:'أحمد',name2:'سارة',date:'2026-12-14',time:'20:00',duration:'3',country:'السعودية',city:'الرياض',location:'الرياض',mapsUrl:'',description:'',videoUrl:'',pdfUrl:'',message:'يسعدنا حضوركم ومشاركتنا هذه المناسبة',package:'الأساسية',capacity:'20',shareAmount:'35',shareLabel:'قيمة القطّة',requireShareConsent:true,allowNamedCompanions:true,waitlistEnabled:true,guestText:'',activityPicking:false,design:{font:'ruqaa',layout:'classic',accent:'#e3bd64',headline:'يسعدنا حضوركم',image:'',showCountdown:true,showMap:true,showQr:true,showMaybe:true,showDecline:true,allowChildren:true,allowNotes:true,photographyPermission:false}};
let restored={};try{restored=JSON.parse(localStorage.getItem('noortoonaDraftV55')||'{}')||{}}catch{}
const state={...defaults,...restored,design:{...defaults.design,...(restored.design||{})}};
const hasSavedDraft=()=>Boolean(localStorage.getItem('noortoonaDraftV55'));
const modal=$('#builderModal'),body=$('#builderBody'),nextBtn=$('#nextBtn'),prevBtn=$('#prevBtn');
const saveDraft=()=>{try{localStorage.setItem('noortoonaDraftV55',JSON.stringify({...state,design:{...state.design,image:''}}))}catch{}};
const occasion=()=>N.occasions.find(x=>x.key===state.occasionKey)||N.occasions[0];
const activity=()=>N.activities.find(x=>x.key===state.activityKey)||N.activities[0];
const groupKey=()=>state.occasionKey==='activity'?state.activityKey:state.occasionKey;
const templates=()=>N.catalog[groupKey()]||N.catalog.custom;
const eventLabel=()=>state.customOccasion||(state.occasionKey==='activity'?'تجمع ونشاط':occasion().label);
const activityLabel=()=>state.occasionKey==='activity'?(state.activityKey==='activityCustom'&&state.customActivity.trim()?state.customActivity.trim():activity().label):'';
const progress=()=>`<div class="journey-progress" role="list" aria-label="مراحل إنشاء الدعوة">${stages.map((label,i)=>`<div class="journey-step ${i+1===state.step?'active':''} ${i+1<state.step?'done':''}" role="listitem"><span>${i+1<state.step?'✓':i+1}</span><small>${label}</small></div>`).join('')}</div>`;
const heading=(title,sub)=>`<div class="builder-heading"><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>`;
const field=(id,label,value,type='text',attrs='')=>`<label class="journey-field"><span>${label}</span><input id="${id}" type="${type}" value="${N.esc(value)}" ${attrs}></label>`;
const setTemplate=(name)=>{state.template=name;state.design.accent=N.templateByName(name).accent;saveDraft();render()};

function openBuilder(key='wedding',resume=false){
  if(!resume){state.occasionKey=key;state.step=1;state.activityPicking=false}
  else{state.step=Math.min(7,Math.max(1,Number(state.step)||1));state.activityPicking=false}
  if(!templates().some(t=>t.name===state.template))state.template=templates()[0].name;
  modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('journey-open');render();
}
function closeBuilder(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('journey-open')}
function renderOccasions(){return `<div class="occasion-choice-grid">${N.occasions.map(o=>`<button type="button" class="occasion-choice ${state.occasionKey===o.key&&!state.activityPicking?'selected':''}" data-occasion="${o.key}"><span>${o.icon}</span><b>${o.label}</b></button>`).join('')}</div>${state.occasionKey==='custom'?`<label class="journey-field custom-occasion"><span>اسم المناسبة</span><input id="customOccasion" maxlength="60" value="${N.esc(state.customOccasion)}" placeholder="اكتب اسم مناسبتك"></label>`:''}`}
function renderActivities(){return `${heading('اختر النشاط','اختر النشاط المناسب لدعوتك')}<div class="activity-choice-grid">${N.activities.map(a=>`<button type="button" class="activity-choice ${state.activityKey===a.key?'selected':''}" data-activity="${a.key}"><span>${a.icon}</span><b>${a.label}</b><small>${a.key==='padel'?'Padel':a.key==='football'?'Football':''}</small></button>`).join('')}</div>${state.activityKey==='activityCustom'?`<label class="journey-field custom-occasion"><span>اسم النشاط</span><input id="customActivity" maxlength="60" value="${N.esc(state.customActivity)}" placeholder="اكتب اسم النشاط"></label>`:''}`}
function renderDetails(){const isActivity=state.occasionKey==='activity';return `${heading(isActivity?`تفاصيل ${activityLabel()}`:'تفاصيل المناسبة','أدخل المعلومات التي ستظهر داخل الدعوة')}<div class="journey-form">${field('name1',isActivity?'اسم التجمع أو الفريق':'الاسم الأول',state.name1)}${isActivity?'':field('name2','الاسم الثاني',state.name2)}${field('date','التاريخ',state.date,'date')}${field('time','الوقت',state.time,'time')}${field('location','المكان',state.location)}${field('city','المدينة',state.city)}<label class="journey-field wide"><span>نص الدعوة</span><textarea id="message" rows="3">${N.esc(state.message)}</textarea></label>${field('mapsUrl','رابط الموقع',state.mapsUrl,'url','placeholder="https://maps.google.com/..."')}${isActivity?`${field('capacity','السعة',state.capacity,'number','min="1" max="500"')}${field('shareAmount','قيمة القطّة للفرد',state.shareAmount,'number','min="0" step="0.5"')}<label class="journey-field wide journey-check"><input id="requireShareConsent" type="checkbox" ${state.requireShareConsent?'checked':''}><span>موافقة الضيف على قطّته وقطّة مرافقيه</span></label><label class="journey-field wide journey-check"><input id="allowNamedCompanions" type="checkbox" ${state.allowNamedCompanions?'checked':''}><span>طلب أسماء المرافقين</span></label><label class="journey-field wide journey-check"><input id="waitlistEnabled" type="checkbox" ${state.waitlistEnabled?'checked':''}><span>تفعيل قائمة الانتظار عند اكتمال العدد</span></label>`:''}</div>`}
function thumb(t){return `<span class="template-art" style="${N.styleFor(t)}"><i></i><span><small>${N.esc(state.occasionKey==='activity'?activityLabel():occasion().label)}</small><b>${N.esc(t.name)}</b></span></span>`}
function renderTemplates(){return `${heading(`اختر قالب ${state.occasionKey==='activity'?activityLabel():occasion().label}`,'اخترنا لك الأنسب أولًا، ويمكنك مقارنة أربعة تصاميم واضحة')}<div class="visual-template-grid">${templates().map((t,i)=>`<button type="button" class="visual-template-card ${state.template===t.name?'selected':''}" data-template="${N.esc(t.name)}">${thumb(t)}${i===0?'<em class="recommended-tag">اختيار نورتونا</em>':''}<span class="template-caption"><b>${N.esc(t.name)}</b>${state.template===t.name?'<i>✓</i>':''}</span></button>`).join('')}</div>`}
function invitePreview(){return `<div class="host-phone"><div class="host-phone-notch"></div>${N.canvas({...state,occasion:eventLabel()})}</div>`}
function renderDesign(){return `${heading('صمّم دعوتك','التخصيص بسيط؛ القالب هو الهوية واللون مجرد لمسة')}<div class="design-workspace"><div class="host-preview-wrap">${invitePreview()}<button type="button" class="guest-preview-link" data-full-preview>معاينة كضيف بالحجم الكامل</button></div><div class="design-controls"><label><span>النص الرئيسي</span><input id="headline" maxlength="70" value="${N.esc(state.design.headline)}"></label><label><span>الخط</span><select id="font"><option value="ruqaa">رقعة أنيق</option><option value="tajawal">تجوال</option><option value="serif">كلاسيكي</option></select></label><label><span>اللون الرئيسي</span><input id="accent" type="color" value="${state.design.accent}"></label><div class="mini-template-switch"><span>تغيير القالب</span>${templates().map(t=>`<button type="button" class="mini-template ${state.template===t.name?'selected':''}" data-template="${N.esc(t.name)}">${thumb(t)}</button>`).join('')}</div><label class="image-upload"><span>استخدام صورتك كخلفية</span><input id="designImage" type="file" accept="image/*"></label></div></div>`}
function parseGuests(){return state.guestText.split(/\r?\n/).map(line=>{const [name,...rest]=line.split(/[,،]/);return{name:name?.trim(),phone:rest.join(',').trim()}}).filter(x=>x.name)}
function renderGuests(){const count=parseGuests().length;return `${heading('أضف الضيوف','كل سطر: اسم الضيف، رقم الجوال')}<div class="guest-entry"><textarea id="guestText" rows="10" placeholder="محمد العتيبي، 0500000000\nخالد الحربي، 0500000001">${N.esc(state.guestText)}</textarea><div class="guest-entry-note"><span>${count} ضيف</span><small>يمكنك أيضًا الإضافة والاستيراد من لوحة المضيف بعد الإنشاء.</small></div></div>`}
function renderReview(){const count=parseGuests().length;return `${heading('راجع دعوتك','هذه المعاينة تستخدم نفس الرسم الذي سيصل للضيف')}<div class="review-grid"><div>${invitePreview()}<button type="button" class="guest-preview-link" data-full-preview>معاينة كضيف</button></div><div class="review-summary"><h3>${N.esc(state.name1)}${state.name2?' و '+N.esc(state.name2):''}</h3><dl><div><dt>النوع</dt><dd>${N.esc(state.occasionKey==='activity'?activityLabel():occasion().label)}</dd></div><div><dt>التاريخ</dt><dd>${N.esc(state.date)}</dd></div><div><dt>الموقع</dt><dd>${N.esc(state.location)}</dd></div><div><dt>القالب</dt><dd>${N.esc(state.template)}</dd></div><div><dt>الضيوف</dt><dd>${count}</dd></div>${state.occasionKey==='activity'?`<div><dt>القطّة</dt><dd>${Number(state.shareAmount||0).toLocaleString('ar-SA')} ر.س للفرد</dd></div>`:''}</dl></div></div>`}
function renderSend(){return `${heading('جاهزة للإرسال','أنشئ المناسبة ثم افتح لوحة المضيف لإرسال الروابط عبر واتساب')}<div class="send-card"><span>✦</span><h3>كل شيء جاهز</h3><p>سيتم إنشاء روابط فريدة للضيوف وحفظ إعدادات الدعوة والقطّة وقائمة الانتظار.</p><div class="package-row">${['البداية','الأساسية','الملكية'].map(p=>`<button type="button" data-package="${p}" class="${state.package===p?'selected':''}">${p}</button>`).join('')}</div></div>`}
function render(){
  $('.builder-progress').style.display='none';let content='';
  if(state.step===1)content=state.activityPicking?renderActivities():`${heading('اختر نوع المناسبة','كل لحظة تستحق دعوة أجمل')}${renderOccasions()}`;
  if(state.step===2)content=renderDetails();if(state.step===3)content=renderTemplates();if(state.step===4)content=renderDesign();if(state.step===5)content=renderGuests();if(state.step===6)content=renderReview();if(state.step===7)content=renderSend();
  body.innerHTML=`${progress()}<div class="journey-save-state"><span>✓ محفوظ تلقائيًا</span><b>الخطوة ${state.step} من ${stages.length}</b></div><div class="journey-content">${content}</div>`;body.scrollTop=0;prevBtn.style.visibility=state.step===1&&!state.activityPicking?'hidden':'visible';nextBtn.textContent=state.step===7?'إنشاء وفتح لوحة المضيف':'التالي ←';nextBtn.disabled=false;bind();requestAnimationFrame(()=>$('.journey-step.active',body)?.scrollIntoView({block:'nearest',inline:'center'}));
}
function bind(){
  $$('[data-occasion]',body).forEach(b=>b.onclick=()=>{state.occasionKey=b.dataset.occasion;state.customOccasion='';if(state.occasionKey==='activity')state.activityPicking=true;else{state.activityPicking=false;state.template=templates()[0].name}saveDraft();render()});
  $$('[data-activity]',body).forEach(b=>b.onclick=()=>{state.activityKey=b.dataset.activity;state.template=templates()[0].name;saveDraft();render()});
  $$('[data-template]',body).forEach(b=>b.onclick=()=>setTemplate(b.dataset.template));$$('[data-package]',body).forEach(b=>b.onclick=()=>{state.package=b.dataset.package;render()});$$('[data-full-preview]',body).forEach(b=>b.onclick=openFullPreview);
  const font=$('#font',body);if(font){font.value=state.design.font;font.onchange=e=>{state.design.font=e.target.value;render()}}const headline=$('#headline',body);if(headline)headline.oninput=e=>{state.design.headline=e.target.value;$('.invite-headline',body).textContent=e.target.value;saveDraft()};const accent=$('#accent',body);if(accent)accent.oninput=e=>{state.design.accent=e.target.value;$('.invite-canvas',body).style.setProperty('--invite-accent',e.target.value);saveDraft()};const upload=$('#designImage',body);if(upload)upload.onchange=handleImage;
  $$('input:not([type=file]),textarea,select',body).forEach(el=>el.addEventListener('input',()=>{clearTimeout(window.__draftSave);window.__draftSave=setTimeout(saveInputs,250)}));
}
function saveInputs(){['customOccasion','customActivity','name1','name2','date','time','location','city','mapsUrl','message','capacity','shareAmount','guestText'].forEach(k=>{const el=$('#'+k,body);if(el)state[k]=el.value});['requireShareConsent','allowNamedCompanions','waitlistEnabled'].forEach(k=>{const el=$('#'+k,body);if(el)state[k]=el.checked});saveDraft()}
function validUrl(v){if(!v)return true;try{return['https:','http:'].includes(new URL(v).protocol)}catch{return false}}
function validate(){if(state.step===1&&state.occasionKey==='custom'&&!state.customOccasion.trim())return'اكتب اسم المناسبة';if(state.step===1&&state.activityPicking&&state.activityKey==='activityCustom'&&!state.customActivity.trim())return'اكتب اسم النشاط';if(state.step===2){if(!state.name1.trim())return'اكتب اسم المناسبة أو الاسم الأول';if(!state.date)return'اختر التاريخ';if(!state.location.trim())return'اكتب مكان المناسبة';if(!validUrl(state.mapsUrl))return'رابط الموقع غير صالح';if(state.occasionKey==='activity'&&Number(state.capacity)<1)return'أدخل سعة صحيحة'}return''}
function handleImage(e){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>10*1024*1024)return toast('اختر صورة صالحة أقل من 10MB');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);state.design.image=canvas.toDataURL('image/jpeg',.82);saveDraft();render()};img.onerror=()=>toast('تعذر قراءة الصورة');img.src=reader.result};reader.readAsDataURL(file)}
function openFullPreview(){let overlay=$('#journeyFullPreview');if(!overlay){overlay=document.createElement('div');overlay.id='journeyFullPreview';overlay.className='journey-full-preview';document.body.appendChild(overlay)}overlay.innerHTML=`<button type="button" aria-label="إغلاق">×</button><div class="full-preview-phone">${N.canvas({...state,occasion:eventLabel()},{guestName:'ضيف نورتونا'})}</div>`;overlay.classList.add('open');$('button',overlay).onclick=()=>overlay.classList.remove('open')}
async function createEvent(){
  nextBtn.disabled=true;nextBtn.textContent='جاري إنشاء المناسبة…';
  try{
    const payload={...state,occasion:eventLabel(),activityType:activityLabel(),title:state.occasionKey==='activity'?state.name1:`${eventLabel()} ${state.name1}${state.name2?' و '+state.name2:''}`,design:{...state.design,occasionKey:state.occasionKey,activityKey:state.activityKey}};
    const res=await fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),data=await res.json();
    if(!res.ok)throw new Error(data.error||'تعذر إنشاء المناسبة');
    const dashboardUrl=`/dashboard?event=${encodeURIComponent(data.event.id)}`;
    localStorage.setItem('noortoonaOwner',JSON.stringify({eventId:data.event.id,ownerToken:data.ownerToken}));
    localStorage.removeItem('noortoonaDraftV55');
    const guests=parseGuests();
    if(guests.length){
      const gr=await fetch('/api/guests',{method:'POST',headers:{'content-type':'application/json','x-noortoona-owner-token':data.ownerToken},body:JSON.stringify({eventId:data.event.id,guests})});
      if(!gr.ok){const gd=await gr.json().catch(()=>({}));toast(`${gd.error||'تم إنشاء المناسبة وتعذر إضافة الضيوف'}. يمكنك إضافتهم من لوحة المضيف.`);setTimeout(()=>location.href=dashboardUrl,1300);return;}
    }
    toast('تم إنشاء مناسبتك بنجاح ✨');setTimeout(()=>location.href=dashboardUrl,500);
  }catch(e){toast(e.message);nextBtn.disabled=false;nextBtn.textContent='إنشاء وفتح لوحة المضيف'}
}
nextBtn.onclick=async()=>{saveInputs();const error=validate();if(error)return toast(error);if(state.step===1&&state.activityPicking){state.activityPicking=false;state.step=2;saveDraft();render();return}if(state.step<7){state.step++;saveDraft();render();return}await createEvent()};prevBtn.onclick=()=>{saveInputs();if(state.step===1&&state.activityPicking){state.activityPicking=false;saveDraft();render();return}if(state.step>1){state.step--;saveDraft();render()}};
$$('[data-start]').forEach(b=>b.onclick=()=>openBuilder(state.occasionKey));$$('[data-close]').forEach(b=>b.onclick=closeBuilder);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeBuilder();$('#journeyFullPreview')?.classList.remove('open')}});
function renderLanding(){
  const grid=$('#occasionGrid');
  if(grid)grid.innerHTML=N.occasions.map(o=>`<button class="occasion-card" data-land-occasion="${o.key}"><span class="occasion-icon">${o.icon}</span><strong>${o.label}</strong><small>ابدأ الآن</small></button>`).join('');
  $$('[data-land-occasion]').forEach(b=>b.onclick=()=>openBuilder(b.dataset.landOccasion));
  const tg=$('#templateGrid');
  if(tg)tg.innerHTML=N.catalog.wedding.map(t=>`<button class="template-card" data-land-template="${N.esc(t.name)}">${thumb(t)}<span class="template-name">${N.esc(t.name)}</span></button>`).join('');
  $$('[data-land-template]').forEach(b=>b.onclick=()=>{state.occasionKey='wedding';state.template=b.dataset.landTemplate;state.step=3;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('journey-open');render()});
  const prices=[
    {name:'البداية',guests:'حتى 50 مدعو',price:'29',items:['دعوة رقمية','رابط فريد لكل ضيف','متابعة الردود']},
    {name:'الأساسية',guests:'حتى 200 مدعو',price:'99',featured:true,items:['كل مزايا البداية','تذكير غير المستجيبين','تصدير قائمة الضيوف']},
    {name:'الملكية',guests:'حتى 500 مدعو',price:'149',items:['كل مزايا الأساسية','قوالب بصرية كاملة','أولوية الدعم']}
  ];
  const pg=$('#priceGrid');
  if(pg)pg.innerHTML=prices.map(p=>`<article class="price-card ${p.featured?'featured':''}">${p.featured?'<span class="price-tag">الأكثر اختيارًا</span>':''}<h3>${p.name}</h3><p>${p.guests}</p><div class="price-number">${p.price}<small> ريال</small></div><ul>${p.items.map(i=>`<li>${i}</li>`).join('')}</ul><button type="button" class="gold-btn" data-land-package="${p.name}" style="width:100%">اختر الباقة</button></article>`).join('');
  $$('[data-land-package]').forEach(b=>b.onclick=()=>{state.package=b.dataset.landPackage;openBuilder(state.occasionKey)});
}
renderLanding();const resumeDraft=$('#resumeDraft');if(resumeDraft&&hasSavedDraft()){resumeDraft.classList.remove('hidden');resumeDraft.onclick=()=>openBuilder(state.occasionKey,true)}const dashboardDemo=$('#dashboardDemoBtn');if(dashboardDemo)dashboardDemo.onclick=()=>{const o=JSON.parse(localStorage.getItem('noortoonaOwner')||'null');o?location.href=`/dashboard?event=${encodeURIComponent(o.eventId)}`:toast('أنشئ مناسبة أولًا لفتح لوحة المضيف')};const login=$('#loginBtn');if(login)login.onclick=()=>dashboardDemo?.click();const mobileBtn=$('#mobileMenuBtn'),mobile=$('#mobileMenu');if(mobileBtn&&mobile)mobileBtn.onclick=()=>{const open=mobile.classList.toggle('open');mobileBtn.setAttribute('aria-expanded',String(open));mobile.setAttribute('aria-hidden',String(!open))};function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200)}
